image: docker:latest
services:
    - docker:dind

stages:
    - build
    - push
    - test
    - deployment
variables:
    DOCKER_USERNAME : abhianv1

build_docker_images:
    stage: build
    script: 
        - ls -la ./UiClikn
        - docker build -t "frontend:latest" ./UiClikn
    tags:
        - docker
push_to_docker_hub:
     stage: push
     script :
         - docker login -u $DOCKER_USERNAME -p $DOCKER_PSA
         - docker info
         - docker tag  frontend:latest "$DOCKER_USERNAME/frontend:latest"
         - docker push "$DOCKER_USERNAME/frontend:latest"

     tags:
         - docker

