stages:
    - build
    - push
    - test
    - deployment
variables:
    DOCKER_USERNAME : abhianv1

build_docker_images:
    stage: build
    script: 
        - docker build -t $DOCKER_USERNAME/frontend UiClikn/.
push_to_docker_hub:
     stage: push
     script :
         - docker login -u $DOCKER_USERNAME -p $DOCKER_PSA
         - docker push $DOCKER_USERNAME/frontend

