image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push
  - test
  - deployment

variables:
  DOCKER_USERNAME: abhianv1
  ACCESS_TOKEN_EXPIRE_DATE: 1d
  PORT: 8000
  REFRESH_TOKEN_EXPIRE_DATE: 30d
  PRODUCTION : true

build_docker_images:
  stage: build
  script: 
    - docker build   -t "backend:latest"  ./BackendClikn
    - docker build   -t "frontend:latest" ./UiClikn
    - rm -rf temp-files || true
  tags:
    - docker

push_to_docker_hub:
  stage: push
  script:
    - echo "$DOCKER_PSA" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker info
    - docker tag frontend:latest "$DOCKER_USERNAME/frontend:latest"
    - docker tag backend:latest "$DOCKER_USERNAME/backend:latest"
    - docker push "$DOCKER_USERNAME/frontend:latest"
    - docker push "$DOCKER_USERNAME/backend:latest"
    - rm -rf temp-files || true
  tags:
    - docker

deploy_to_ec2:
  stage: test
  script:
    - echo "$EC2_PEM" | base64 -d > Docker-image.pem
    - chmod 400 Docker-image.pem
    - |
      ssh -o StrictHostKeyChecking=no -i "Docker-image.pem" ubuntu@ec2-3-93-179-156.compute-1.amazonaws.com <<EOF
      sudo apt install docker-compose-plugin -y
      docker compose version
      mkdir -p ~/BackendClikn/src
      cat <<EOT > ~/BackendClikn/src/.env
      ACCESS_TOKEN_EXPIRE_DATE=$ACCESS_TOKEN_EXPIRE_DATE
      PORT=$PORT
      REFRESH_TOKEN_EXPIRE_DATE=$REFRESH_TOKEN_EXPIRE_DATE
      PRODUCTION=$PRODUCTION
      ACCESS_TOKEN=$ACCESS_TOKEN
      GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      MONGODB_URI=$MONGODB_URI
      REFRESH_TOKEN=$REFRESH_TOKEN
      EOT
      curl -O https://gitlab.com/abhinavrastogi986/clikn/-/raw/main/docker-compose.yml
      docker compose down
      docker compose  up --build  -d
      docker ps -a
      exit
      EOF


