version: "3.9"

services:

    frontend:
        image: abhianv1/frontend
        ports:
            - 5173:5173
        networks:
            - clikn
        container_name: frontend
        environment:
            - VITE_API_URL=https://3.93.179.156:8000
        depends_on:
            - backend
        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://backend:8000 || exit 1" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
    backend:
        image: abhianv1/backend
        ports:
            - 8080:8000
            - 8000:8000
        container_name: backend
        env_file:
            - ~/BackendClikn/src/.env
        networks:
            - clikn
networks:
    clikn:
        name: clikn
